### PR TITLE
Sketch & Description 

### PR DESCRIPTION
**Pull request by nicolebid**
I updated the sketch and wrote the description for it in an md file. If you like you can add your parts for the proposal in this file once its merged.

### CODE REVIEW

**Review by Marcony1 — APPROVED** [review]
Agree with the changes

**Comment by fohy24** [comment]
Looks like the proposal should be named `m1_proposal.md`. Could you please rename it? Replacing the existing `m1_proposal.md` should be good.

**Review by rafecchang — APPROVED** [review]
nice!

**Review by rafecchang — APPROVED** [review]
nice!

**Pull request merged**
