### PR TITLE
section_1

### PR DESCRIPTION
**Pull request by rafecchang**

### CODE REVIEW

**Comment by Marcony1** [comment]
LGTM

**Review by Marcony1 — CHANGES_REQUESTED** [review]
These seem to be the instructions of the Milestone. Would this be the readme file?

**Comment by rafecchang** [comment]
This is what we're submitting for the milestone I suppose? I have wrote section one here. There are a lot of unnecessary descriptions that we can delete.

**Comment by Marcony1** [comment]
> LGTM
 


> This is what we're submitting for the milestone I suppose? I have wrote section one here. There are a lot of unnecessary descriptions that we can delete.

Oh, I see. Then, I think that the file should be named "m1_proposal.md" under the "reports" folder. Could you create such folder and change the name, please?

**Comment by rafecchang** [comment]
I am not sure what happened, but this file is no longer on my local. We can go through this pull request first then do the changes.

**Comment by Marcony1** [comment]
> I am not sure what happened, but this file is no longer on my local. We can go through this pull request first then do the changes.

All right, merging.

**Review by Marcony1 — APPROVED** [review]

**Pull request merged**
